// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq9CQngtezBd5RRi0lThnw7bnBOSzq_XU',
    appId: '1:650820330118:web:3de039d277150228826707',
    messagingSenderId: '650820330118',
    projectId: 'first-app-aefe6',
    authDomain: 'first-app-aefe6.firebaseapp.com',
    databaseURL: 'https://first-app-aefe6-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-aefe6.firebasestorage.app',
    measurementId: 'G-VV6LSGD5XL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-_FV2Wuv8zQzBXNywOJeYwGLGUvKQN0M',
    appId: '1:650820330118:android:793d91925c3e6ae7826707',
    messagingSenderId: '650820330118',
    projectId: 'first-app-aefe6',
    databaseURL: 'https://first-app-aefe6-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-aefe6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhdOCOilOW3S5E_NsTR35SHkOE_1nuFUw',
    appId: '1:650820330118:ios:c729f4187d1148ba826707',
    messagingSenderId: '650820330118',
    projectId: 'first-app-aefe6',
    databaseURL: 'https://first-app-aefe6-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-aefe6.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhdOCOilOW3S5E_NsTR35SHkOE_1nuFUw',
    appId: '1:650820330118:ios:c729f4187d1148ba826707',
    messagingSenderId: '650820330118',
    projectId: 'first-app-aefe6',
    databaseURL: 'https://first-app-aefe6-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-aefe6.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAq9CQngtezBd5RRi0lThnw7bnBOSzq_XU',
    appId: '1:650820330118:web:32687cf64998d3a2826707',
    messagingSenderId: '650820330118',
    projectId: 'first-app-aefe6',
    authDomain: 'first-app-aefe6.firebaseapp.com',
    databaseURL: 'https://first-app-aefe6-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-aefe6.firebasestorage.app',
    measurementId: 'G-PGN4JTCHG1',
  );
}
